### ISSUE TITLE
Wrong CraftingTable interaction with this mod enabled

### ISSUE THREAD

**Issue by MCcber** [VoxelMap2/VoxelMap#12] opened 2023-07-16 14:01 UTC
The game version is 1.20.1
The client is Fabric

For example, if I have 6 oak logs and 6 dark oak logs, when I open the workbench, the wooden trap door will tell the player to right-click to expand and select the specified branch for synthesis, but right-clicking cannot expand this option at this time interface

I don't know yet if there are other factors indirectly causing this problem with this mod, but it happened

**Comment by TheAlgorithm476** [comment] 2023-07-19 09:56
Are you sure VoxelMap is the cause of this? VoxelMap does not have anything influencing crafting. Does it occur when VoxelMap is not installed, or with other mods/combos?

**Comment by MCcber** [comment] 2023-07-19 13:36
> Are you sure VoxelMap is the cause of this? VoxelMap does not have anything influencing crafting. Does it occur when VoxelMap is not installed, or with other mods/combos?

I don't know the root cause of this, but on the surface it seems that the mod is turned off and it is fine, and it is broken when it is turned on
I just came here to remind, if all the codes of this map have nothing to do with the craftingTable, then it is my personal problem

**Comment by TheAlgorithm476** [comment] 2023-07-19 20:13
It's odd, but will investigate

**Comment by TheAlgorithm476** [comment] 2023-07-19 20:16
Can you check if the issue still occurs if you have no mods other than VoxelMap installed? Preferably a fresh instance of Minecraft, with only Fabric API and VoxelMap installed, and check if it still occurs. This will either deny or confirm VoxelMap's doing in this.

**Comment by MCcber** [comment] 2023-07-21 05:04
> Can you check if the issue still occurs if you have no mods other than VoxelMap installed? Preferably a fresh instance of Minecraft, with only Fabric API and VoxelMap installed, and check if it still occurs. This will either deny or confirm VoxelMap's doing in this.

I have confirmed that the problem I mentioned will indeed occur when only fabric API and Voxelmap are turned on. Turning off Voxelmap will not affect it. I also downloaded 1.17 and tested the old version of Voxelmap. I found that the old version does not have this problem (that is, the last version developed by the original author)

**Comment by TheAlgorithm476** [comment] 2023-07-21 09:31
I'll add your issue to the bug tracker, to be patched when time comes to it

**Comment by TheAlgorithm476** [comment] 2023-07-23 14:30
Hello again. I have just tried your outlined method of reproducing this issue, and I have not managed to replicate it. Can you please give me a more detailed guide on how you got this bug, so we can get this fixed? Thanks

**Comment by MCcber** [comment] 2023-07-23 14:35
> Hello again. I have just tried your outlined method of reproducing this issue, and I have not managed to replicate it. Can you please give me a more detailed guide on how you got this bug, so we can get this fixed? Thanks

It may be related to my device. At that time, I was building in a friend’s server. There were two kinds of wood planks, oak and spruce. After opening the craftingTable, the UI couldn’t be expanded. Sorry, I can’t reproduce this bug and I don’t know why it appeared.

**Comment by TheAlgorithm476** [comment] 2023-07-23 14:37
I am closing this issue then. If you're able to reproduce it, and able to give instruction on how to reproduce it, feel free to reopen.

**Closed as completed by TheAlgorithm476** 2023-07-23 14:37 UTC

**Comment by MCcber** [comment] 2023-07-23 14:39
> I am closing this issue then. If you're able to reproduce it, and able to give instruction on how to reproduce it, feel free to reopen.

ok ok, actually I don't understand why a map mod can affect the craftingTable
